[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --worker-class eventlet -w 1 'app:create_app()' --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
